name: Lockette
main: org.soraworld.lockette.Lockette
author: Himmelt,connection_lost
softdepend: [WorldGuard, Residence, Towny, ProtocolLib, Factions]
version: 1.7.10-0.0.1
description: >
             Lockette is a chest protection plugin for Bukkit. It delivers a lot of performance enhancements and feature options.
commands:
   lockette:
      permission: lockette.command
      usage: |
         /lock
      aliases: [lock, lockette, lockit]
permissions:
   lockette.command:
      description: Command permission for Lockette
      default: true
   lockette.lock:
      description: Basic lock permission
      default: true
   lockette.edit:
      description: Edit sign permission
      default: true